---
apiVersion: v1
kind: Secret
metadata:
  name: azure-openai-secret
type: Opaque
data:
  # This uses the base64-encoded API key from the quickstart script
  # The quickstart.sh script will substitute ${API_KEY} with the base64-encoded value
  token: ${API_KEY}
